/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package utilerias;

import analisis.FrmCatalogoAnalisis;
import analisis.FrmRegistroSolicitud;
import resultados.FrmIngresoResultados;


/**
 *
 * @author cinca
 */
public class pnlMenuLateral extends javax.swing.JPanel {

    /**
     * Creates new form pnlMenuLateral
     */
    public pnlMenuLateral() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSolicitud = new javax.swing.JButton();
        btnCatalogo = new javax.swing.JButton();
        btnDatos = new javax.swing.JButton();
        btnResultados = new javax.swing.JButton();

        setBackground(new java.awt.Color(166, 217, 243));

        btnSolicitud.setBackground(new java.awt.Color(166, 217, 243));
        btnSolicitud.setFont(new java.awt.Font("Corbel", 0, 24)); // NOI18N
        btnSolicitud.setForeground(new java.awt.Color(0, 0, 0));
        btnSolicitud.setText("Registro de solicitud");
        btnSolicitud.setBorder(null);
        btnSolicitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSolicitudActionPerformed(evt);
            }
        });

        btnCatalogo.setBackground(new java.awt.Color(166, 217, 243));
        btnCatalogo.setFont(new java.awt.Font("Corbel", 0, 24)); // NOI18N
        btnCatalogo.setForeground(new java.awt.Color(0, 0, 0));
        btnCatalogo.setText("Catalogo de analisis");
        btnCatalogo.setBorder(null);
        btnCatalogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCatalogoActionPerformed(evt);
            }
        });

        btnDatos.setBackground(new java.awt.Color(166, 217, 243));
        btnDatos.setFont(new java.awt.Font("Corbel", 0, 24)); // NOI18N
        btnDatos.setForeground(new java.awt.Color(0, 0, 0));
        btnDatos.setText("Ingresar datos masivos");
        btnDatos.setBorder(null);
        btnDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatosActionPerformed(evt);
            }
        });

        btnResultados.setBackground(new java.awt.Color(166, 217, 243));
        btnResultados.setFont(new java.awt.Font("Corbel", 0, 24)); // NOI18N
        btnResultados.setForeground(new java.awt.Color(0, 0, 0));
        btnResultados.setText("Resultados");
        btnResultados.setBorder(null);
        btnResultados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResultadosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCatalogo, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnResultados, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(btnCatalogo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnResultados, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(233, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSolicitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSolicitudActionPerformed
        FrmRegistroSolicitud pantalla= new FrmRegistroSolicitud();
        pantalla.setVisible(true);
    }//GEN-LAST:event_btnSolicitudActionPerformed

    private void btnCatalogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCatalogoActionPerformed
        FrmCatalogoAnalisis pantalla = new FrmCatalogoAnalisis();
        pantalla.setVisible(true);
    }//GEN-LAST:event_btnCatalogoActionPerformed

    private void btnDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatosActionPerformed
       
    }//GEN-LAST:event_btnDatosActionPerformed

    private void btnResultadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResultadosActionPerformed
        FrmIngresoResultados pantalla = new FrmIngresoResultados();
        pantalla.setVisible(true);
        
    }//GEN-LAST:event_btnResultadosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCatalogo;
    private javax.swing.JButton btnDatos;
    private javax.swing.JButton btnResultados;
    private javax.swing.JButton btnSolicitud;
    // End of variables declaration//GEN-END:variables
}
