/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package analisis;

import dto.AnalisisDTO;
import interfaces.IAnalisisNegocio;
import utilerias.ButtonRenderer;
import utilerias.ButtonEditor;
import javax.swing.JCheckBox;
import javax.swing.SwingUtilities;
import utilerias.EditarButtonEditor;
import utilerias.EditarButtonRenderer;

/**
 * Ventana (JFrame) que representa el catálogo o registro de parámetros
 * pertenecientes a un análisis clínico específico. Permite visualizar, agregar,
 * editar y eliminar los parámetros antes de guardar el análisis completo en la
 * base de datos.
 *
 * @author cinca luisf
 */
public class FrmCatalogoParametros extends javax.swing.JFrame {

    /**
     * Interfaz de la capa de negocio utilizada para guardar el análisis y sus
     * parámetros.
     */
    private IAnalisisNegocio analisisNegocio;
    /**
     * Objeto de transferencia de datos (DTO) que contiene la información del
     * análisis en curso y la lista de parámetros asociados.
     */
    private AnalisisDTO analisisDTO;

    /**
     * Constructor por defecto de la clase FrmCatalogoParametros. Inicializa los
     * componentes gráficos y configura la tabla vacía.
     */
    public FrmCatalogoParametros() {
        initComponents();
        configurarTabla();

    }

    /**
     * Constructor sobrecargado de la clase FrmCatalogoParametros. Se utiliza
     * para recibir el contexto del análisis que se está creando/editando.
     *
     * @param analisisNegocio Instancia de la capa de negocio para operaciones
     * de análisis.
     * @param analisisDTO Objeto DTO con los datos del análisis y sus parámetros
     * actuales.
     */
    public FrmCatalogoParametros(IAnalisisNegocio analisisNegocio, AnalisisDTO analisisDTO) {
        this.analisisNegocio = analisisNegocio;
        this.analisisDTO = analisisDTO;
        initComponents();
        llenarTabla();
        configurarTabla();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnSiguiente = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnCancelar = new javax.swing.JButton();
        btnAgregarParametro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(969, 589));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N
        jLabel2.setText("Registro de parametros");

        btnSiguiente.setBackground(new java.awt.Color(102, 255, 102));
        btnSiguiente.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        btnSiguiente.setText("Siguiente");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Nota", "Tipo de muestra", "Valores", "Eliminar"
            }
        ));
        jTable1.setRowHeight(35);
        jScrollPane2.setViewportView(jTable1);

        btnCancelar.setBackground(new java.awt.Color(153, 153, 153));
        btnCancelar.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnAgregarParametro.setBackground(new java.awt.Color(153, 255, 255));
        btnAgregarParametro.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        btnAgregarParametro.setText("+ Agregar parametro");
        btnAgregarParametro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarParametroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(295, 295, 295)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAgregarParametro, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(678, 678, 678)
                            .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 895, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 32, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel2)
                        .addGap(0, 39, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAgregarParametro, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
     * Evento desencadenado al hacer clic en el botón "+ Agregar parametro".
     * Abre el formulario FrmRegistroParametro, pasando el contexto actual para
     * agregar un nuevo parámetro a la lista, y cierra la ventana actual.
     *
     * @param evt Evento de acción de la interfaz.
     */
    private void btnAgregarParametroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarParametroActionPerformed
        FrmRegistroParametro frmRegistro = new FrmRegistroParametro(this.analisisNegocio, this.analisisDTO);
        frmRegistro.setLocationRelativeTo(this);
        frmRegistro.setVisible(true);

        this.dispose();

    }//GEN-LAST:event_btnAgregarParametroActionPerformed
    /**
     * Evento desencadenado al hacer clic en el botón "Siguiente". Valida que
     * exista al menos un parámetro registrado. Si la validación es exitosa,
     * guarda el análisis junto con sus parámetros en la base de datos a través
     * de la capa de negocio, muestra un mensaje de éxito y redirige al catálogo
     * principal.
     *
     * @param evt Evento de acción de la interfaz.
     */
    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        if (this.analisisDTO.getParametros().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Debes agregar al menos un parámetro al análisis antes de guardar.",
                    "Advertencia", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            this.analisisNegocio.guardarAnalisis(this.analisisDTO);

            javax.swing.JOptionPane.showMessageDialog(this, "¡Análisis y parámetros registrados con éxito!");

            FrmCatalogoAnalisis frmCatalogo = new FrmCatalogoAnalisis();
            frmCatalogo.setLocationRelativeTo(this);
            frmCatalogo.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
            frmCatalogo.setVisible(true);

            this.dispose();
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Error al guardar en la base de datos: " + ex.getMessage(),
                    "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnSiguienteActionPerformed
    /**
     * Evento desencadenado al hacer clic en el botón "Cancelar". Cancela el
     * registro actual del análisis, descarta los datos y devuelve al usuario a
     * la pantalla del catálogo principal de análisis.
     *
     * @param evt Evento de acción de la interfaz.
     */
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        FrmCatalogoAnalisis frmCatalogo = new FrmCatalogoAnalisis();
        frmCatalogo.setLocationRelativeTo(this);
        frmCatalogo.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
        frmCatalogo.setVisible(true);

        this.dispose();    }//GEN-LAST:event_btnCancelarActionPerformed
    /**
     * Llena el modelo de la tabla (jTable1) iterando sobre la lista de
     * parámetros almacenada en analisisDTO. Muestra el nombre, nota y tipo de
     * valor del parámetro, además de preparar las columnas de "Editar" y
     * "Eliminar".
     */
    private void llenarTabla() {
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        modelo.setRowCount(0);

        if (this.analisisDTO != null && this.analisisDTO.getParametros() != null) {
            for (dto.ParametroDTO param : this.analisisDTO.getParametros()) {
                modelo.addRow(new Object[]{
                    param.getNombre(),
                    param.getNota(),
                    param.getTipoValor(),
                    "Editar",
                    "Eliminar"
                });
            }
        }
    }

    /**
     * Elimina un parámetro específico de la lista de parámetros del DTO en
     * función del índice de la fila seleccionada y posteriormente actualiza la
     * tabla.
     *
     * @param rowIndex Índice de la fila seleccionada en la tabla que
     * corresponde al parámetro a eliminar.
     */
    public void eliminarParametro(int rowIndex) {
        if (this.analisisDTO != null && this.analisisDTO.getParametros() != null) {
            this.analisisDTO.getParametros().remove(rowIndex);
            llenarTabla();
        }
    }

    /**
     * Configura el comportamiento visual e interactivo de las columnas de
     * acciones de la tabla. Asigna renderizadores (Renderers) y editores
     * (Editors) personalizados para convertir las celdas de las columnas
     * "Valores" (índice 3) y "Eliminar" (índice 4) en botones funcionales.
     */
    public void configurarTabla() {
        int indiceColumnaEditar = 3;
        int indiceColumnaEliminar = 4;

        jTable1.getColumnModel().getColumn(indiceColumnaEditar)
                .setCellRenderer(new EditarButtonRenderer());

        jTable1.getColumnModel().getColumn(indiceColumnaEliminar)
                .setCellRenderer(new ButtonRenderer());

        jTable1.getColumnModel().getColumn(indiceColumnaEditar)
                .setCellEditor(new EditarButtonEditor(new JCheckBox(), () -> {

                    Object filaObj = jTable1.getClientProperty("filaSeleccionada");

                    if (filaObj != null) {
                        int filaSeleccionada = (int) filaObj;
                        System.out.println("Editar valores de la fila: " + filaSeleccionada);

                        dto.ParametroDTO parametroSeleccionado = this.analisisDTO.getParametros().get(filaSeleccionada);

                        FrmValoresRango frmValores = new FrmValoresRango(parametroSeleccionado);
                        frmValores.setLocationRelativeTo(this);
                        frmValores.setVisible(true);
                    }
                }));

        jTable1.getColumnModel().getColumn(indiceColumnaEliminar)
                .setCellEditor(new ButtonEditor(new JCheckBox(), () -> {

                    Object filaObj = jTable1.getClientProperty("filaSeleccionada");

                    if (filaObj != null) {
                        int filaSeleccionada = (int) filaObj;
                        System.out.println("Eliminar parámetro de la fila: " + filaSeleccionada);

                        SwingUtilities.invokeLater(() -> {
                            eliminarParametro(filaSeleccionada);
                        });
                    }
                }));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarParametro;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
