package analisis;

import dto.AnalisisDTO;
import interfaces.IAnalisisNegocio;
import interfaces.IPruebaNegocio;
import itson.org.entidades.AnalisisEntidad;
import itson.org.entidades.ClienteEntidad;
import itson.org.entidades.DetallesPruebaEntidad;
import itson.org.entidades.DoctorEntidad;
import itson.org.entidades.ParametroEntidad;
import itson.org.entidades.PruebaEntidad;
import itson.org.negocio.AnalisisNegocio;
import itson.org.negocio.PruebaNegocio;
import java.util.List;

/**
 *
 * @author hp
 */
public class FrmRegistroSolicitud extends javax.swing.JFrame {

    private IPruebaNegocio prueba = new PruebaNegocio();
    private IAnalisisNegocio analisi = new AnalisisNegocio();
    private List<ClienteEntidad> listaClientesGlobal;
    private List<DoctorEntidad> listaDoctoresGlobal;

    public FrmRegistroSolicitud() {

        initComponents();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        llenarComboBoxDoctores();
        llenarPanelAnalis();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LblTitulo = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        LblCliente = new javax.swing.JLabel();
        ComboClientes = new javax.swing.JComboBox<>();
        LblDoctor = new javax.swing.JLabel();
        ComboDoctor = new javax.swing.JComboBox<>();
        LblAnalisis = new javax.swing.JLabel();
        PnlAnalisis = new javax.swing.JPanel();
        btnRegistrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        LblTitulo.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N
        LblTitulo.setText("Registro de solicitud");

        btnCancelar.setBackground(new java.awt.Color(153, 153, 153));
        btnCancelar.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        LblCliente.setText("Cliente:");

        ComboClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboClientesActionPerformed(evt);
            }
        });

        LblDoctor.setText("Doctor:");

        LblAnalisis.setText("Analisis:");

        PnlAnalisis.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout PnlAnalisisLayout = new javax.swing.GroupLayout(PnlAnalisis);
        PnlAnalisis.setLayout(PnlAnalisisLayout);
        PnlAnalisisLayout.setHorizontalGroup(
            PnlAnalisisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 494, Short.MAX_VALUE)
        );
        PnlAnalisisLayout.setVerticalGroup(
            PnlAnalisisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 318, Short.MAX_VALUE)
        );

        btnRegistrar.setBackground(new java.awt.Color(102, 255, 102));
        btnRegistrar.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(169, 169, 169))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LblAnalisis, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(LblCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ComboClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(LblDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ComboDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(PnlAnalisis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(63, 63, 63)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(LblTitulo)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblCliente)
                    .addComponent(ComboClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblDoctor)
                    .addComponent(ComboDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(LblAnalisis)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PnlAnalisis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();    }//GEN-LAST:event_btnCancelarActionPerformed

    private void ComboClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboClientesActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        try {
            int indexCliente = ComboClientes.getSelectedIndex();
            int indexDoctor = ComboDoctor.getSelectedIndex();

            if (indexCliente == -1 || indexDoctor == -1) {
                javax.swing.JOptionPane.showMessageDialog(this, "Debe seleccionar un Cliente y un Doctor.");
                return;
            }

            ClienteEntidad clienteSeleccionado = listaClientesGlobal.get(indexCliente);
            DoctorEntidad doctorSeleccionado = listaDoctoresGlobal.get(indexDoctor);

            List<AnalisisDTO> analisisElegidos = new java.util.ArrayList<>();
            for (java.awt.Component comp : PnlAnalisis.getComponents()) {
                if (comp instanceof javax.swing.JCheckBox) {
                    javax.swing.JCheckBox chk = (javax.swing.JCheckBox) comp;
                    if (chk.isSelected()) {
                        AnalisisDTO dto = (AnalisisDTO) chk.getClientProperty("data");
                        if (dto != null) {
                            analisisElegidos.add(dto);
                        }
                    }
                }
            }

            if (analisisElegidos.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Debe seleccionar al menos un análisis.");
                return;
            }

            PruebaEntidad nuevaSolicitud = new PruebaEntidad();
            nuevaSolicitud.setFolio("FOL-" + System.currentTimeMillis());
            nuevaSolicitud.setFechaHora(java.time.LocalDateTime.now());
            nuevaSolicitud.setCliente(clienteSeleccionado);
            nuevaSolicitud.setDoctor(doctorSeleccionado);

            List<DetallesPruebaEntidad> detalles = new java.util.ArrayList<>();
            for (AnalisisDTO analisisDTO : analisisElegidos) {

                List<ParametroEntidad> parametrosDelAnalisis = analisi.obtenerParametrosPorAnalisisId(analisisDTO.getId());

                if (parametrosDelAnalisis != null) {
                    for (ParametroEntidad parametro : parametrosDelAnalisis) {

                        DetallesPruebaEntidad detalle = new DetallesPruebaEntidad();

                        detalle.setPrueba(nuevaSolicitud);
                        detalle.setObservaciones("");
                        detalle.setParametro(parametro);

                        detalles.add(detalle);
                    }
                }
            }

            nuevaSolicitud.setDetalles(detalles);

            prueba.guardarSolicitud(nuevaSolicitud);

            javax.swing.JOptionPane.showMessageDialog(this, "Solicitud registrada con éxito.");
            this.dispose(); // Cerrar ventana

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al guardar la solicitud: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboClientes;
    private javax.swing.JComboBox<String> ComboDoctor;
    private javax.swing.JLabel LblAnalisis;
    private javax.swing.JLabel LblCliente;
    private javax.swing.JLabel LblDoctor;
    private javax.swing.JLabel LblTitulo;
    private javax.swing.JPanel PnlAnalisis;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private void llenarComboBoxDoctores() {
        try {
            listaDoctoresGlobal = prueba.obtenerTodosDoctores();
            listaClientesGlobal = prueba.obtenerTodosClientes();

            ComboDoctor.removeAllItems();
            ComboClientes.removeAllItems();

            for (DoctorEntidad doc : listaDoctoresGlobal) {
                ComboDoctor.addItem(doc.getNombre() + " " + doc.getApellidoPaterno());
            }
            for (ClienteEntidad cli : listaClientesGlobal) {
                ComboClientes.addItem(cli.getNombre() + " " + cli.getApellidoPaterno());
            }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }

    private void llenarPanelAnalis() {
        try {
            List<AnalisisDTO> listaAnalisis = analisi.obtenerAnalisis();

            PnlAnalisis.removeAll();

            PnlAnalisis.setLayout(new javax.swing.BoxLayout(PnlAnalisis, javax.swing.BoxLayout.Y_AXIS));

            for (AnalisisDTO dto : listaAnalisis) {
                String textoMostrar = dto.getNombre();
                javax.swing.JCheckBox chk = new javax.swing.JCheckBox(textoMostrar);

                chk.putClientProperty("data", dto);

                chk.setFont(new java.awt.Font("Corbel", 0, 14));

                PnlAnalisis.add(chk);
            }

            PnlAnalisis.revalidate();
            PnlAnalisis.repaint();

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al cargar analisis: " + e.getMessage());
        }
    }
}
